apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporter
  labels:
    app: reporter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reporter
  template:
    metadata:
      labels:
        app: reporter
    spec:
      containers:
        - name: reporter
          image: tecke/weather-network-reporter:latest
          ports:
            - containerPort: 8000
